/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Table: typeof import('./src/components/Table/index.vue')['default']
    TableImage: typeof import('./src/components/Table/components/TableImage/index.vue')['default']
    TableText: typeof import('./src/components/Table/components/TableText/index.vue')['default']
  }
}
